version: '3.5'

services:
  go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      target: build
    depends_on:
      - db
    ports:
        - 8080:8080
    volumes:
        - ./src:/go/src
    tty:
      true
    environment:
      TZ: Asia/Tokyo
      DBMS: mysql
      USER: root
      PASS: root
      PROTOCOL: tcp(db:3306)
      DBNAME: godock
  db:
    build: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: godock
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo